runtime: python
env: flex
api_version: 1

runtime_config:
    python_version: 3

handlers:
- url: /SmsResponse
  script: Twilio_Routing.RecivedSms

- url: /CallResponse
  script: Twilio_Routing.ReceivedCall